# agent opcode (https://github.com/dannyben/opcode)

build: go build .
#? Build with Go cache outside the shared folder

test: go test ./... "$@"
#? Run tests with Go cache outside the shared folder

check:
  gofmt -w .
  go vet ./...
  go test ./...
#? Format, vet, and test with Go cache outside the shared folder
